[package]
name = "cod-oracle"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
dike-types = { workspace = true }
dike-math = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
market-registry = { path = "../market_registry" }
collateral-vault = { path = "../collateral_vault" }
council-of-dike = { path = "../council_of_dike" }
